"""Fix relation between files and users

Revision ID: 0d30f5919aaa
Revises: c7c7f706ffff
Create Date: 2025-12-04 09:00:13.139759

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d30f5919aaa'
down_revision = 'c7c7f706ffff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('uploaded_by_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False))
    op.drop_constraint(op.f('file_ibfk_1'), 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'users', ['uploaded_by_id'], ['id'])
    op.drop_column('file', 'uploaded_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('uploaded_by', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(op.f('file_ibfk_1'), 'file', 'users', ['uploaded_by'], ['id'])
    op.drop_column('file', 'uploaded_by_id')
    # ### end Alembic commands ###
