"""Add Migration Ids

Revision ID: 1141fce1a4c4
Revises: 5d11af59140d
Create Date: 2025-11-25 07:35:58.738141

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1141fce1a4c4'
down_revision = '5d11af59140d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cathegories', sa.Column('migration_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cathegories_migration_id'), 'cathegories', ['migration_id'], unique=False)
    op.add_column('congresses', sa.Column('migration_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_congresses_migration_id'), 'congresses', ['migration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_congresses_migration_id'), table_name='congresses')
    op.drop_column('congresses', 'migration_id')
    op.drop_index(op.f('ix_cathegories_migration_id'), table_name='cathegories')
    op.drop_column('cathegories', 'migration_id')
    # ### end Alembic commands ###
