"""Add relationshipkey between sponsoring and company

Revision ID: 12a17a8df844
Revises: c3d61ac02298
Create Date: 2025-12-15 11:55:11.308482

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '12a17a8df844'
down_revision = 'c3d61ac02298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsorings', sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'sponsorings', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sponsorings', type_='foreignkey')
    op.drop_column('sponsorings', 'company_id')
    # ### end Alembic commands ###
