"""Add native coutry name

Revision ID: 1534389bac09
Revises: f008fe2bd0fc
Create Date: 2025-11-25 07:01:54.725744

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1534389bac09'
down_revision = 'f008fe2bd0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('name_native', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'name_native')
    # ### end Alembic commands ###
