"""Update the Location matching the nominatim search and adding link for Webinars

Revision ID: 322851ef48bf
Revises: aa74049fe81d
Create Date: 2025-12-02 08:25:30.893092

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '322851ef48bf'
down_revision = 'aa74049fe81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('road', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('locations', sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('locations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('locations', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('locations', sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('locations', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('locations', 'link')
    op.drop_column('locations', 'longitude')
    op.drop_column('locations', 'latitude')
    op.drop_column('locations', 'number')
    op.drop_column('locations', 'road')
    # ### end Alembic commands ###
