"""Add Programm and EventSessions

Revision ID: 4cd585af1f57
Revises: ad5e83e05dea
Create Date: 2025-12-18 07:01:03.965416

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4cd585af1f57'
down_revision = 'ad5e83e05dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_sessions_event_id'), 'event_sessions', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_sessions_start_time'), 'event_sessions', ['start_time'], unique=False)
    op.create_table('programms',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('LECTURE', 'WORKSHOP', 'DEMO', 'NETWORKING', 'BREAK', 'KEYNOTE', 'OTHER', name='programmtype'), nullable=False),
    sa.Column('location_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('speaker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['event_sessions.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programms_location_id'), 'programms', ['location_id'], unique=False)
    op.create_index(op.f('ix_programms_session_id'), 'programms', ['session_id'], unique=False)
    op.create_index(op.f('ix_programms_speaker_id'), 'programms', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_programms_start_time'), 'programms', ['start_time'], unique=False)
    op.create_index(op.f('ix_programms_title'), 'programms', ['title'], unique=False)
    op.create_index(op.f('ix_programms_type'), 'programms', ['type'], unique=False)
    op.add_column('events', sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('events', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('events', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'language')
    op.drop_column('events', 'url')
    op.drop_column('events', 'subject')
    op.drop_index(op.f('ix_programms_type'), table_name='programms')
    op.drop_index(op.f('ix_programms_title'), table_name='programms')
    op.drop_index(op.f('ix_programms_start_time'), table_name='programms')
    op.drop_index(op.f('ix_programms_speaker_id'), table_name='programms')
    op.drop_index(op.f('ix_programms_session_id'), table_name='programms')
    op.drop_index(op.f('ix_programms_location_id'), table_name='programms')
    op.drop_table('programms')
    op.drop_index(op.f('ix_event_sessions_start_time'), table_name='event_sessions')
    op.drop_index(op.f('ix_event_sessions_event_id'), table_name='event_sessions')
    op.drop_table('event_sessions')
    # ### end Alembic commands ###
