"""c_cat to match the cathegories

Revision ID: 506ee2fdaaab
Revises: 1141fce1a4c4
Create Date: 2025-11-25 07:45:57.588044

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '506ee2fdaaab'
down_revision = '1141fce1a4c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('congresses', sa.Column('c_cat', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('congresses', 'c_cat')
    # ### end Alembic commands ###
