"""add foreign key user_id to login otp

Revision ID: 784337e29f40
Revises: f5e7f224d403
Create Date: 2025-11-17 13:33:44.630448

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '784337e29f40'
down_revision = 'f5e7f224d403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loginotp', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_loginotp_user_id'), 'loginotp', ['user_id'], unique=False)
    op.create_foreign_key(None, 'loginotp', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loginotp', type_='foreignkey')
    op.drop_index(op.f('ix_loginotp_user_id'), table_name='loginotp')
    op.drop_column('loginotp', 'user_id')
    # ### end Alembic commands ###
