"""create object permissions table and add bypass_object_scope to roles

Revision ID: 78eff1f641f2
Revises: b104f2f7f298
Create Date: 2025-12-17 08:10:01.453925

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '78eff1f641f2'
down_revision = 'b104f2f7f298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_permissions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('can_show', sa.Boolean(), nullable=False),
    sa.Column('can_update', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_permissions_object_id'), 'object_permissions', ['object_id'], unique=False)
    op.create_index(op.f('ix_object_permissions_resource'), 'object_permissions', ['resource'], unique=False)
    op.create_index(op.f('ix_object_permissions_user_id'), 'object_permissions', ['user_id'], unique=False)
    op.add_column('roles', sa.Column('bypass_object_scope', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_roles_bypass_object_scope'), 'roles', ['bypass_object_scope'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_bypass_object_scope'), table_name='roles')
    op.drop_column('roles', 'bypass_object_scope')
    op.drop_index(op.f('ix_object_permissions_user_id'), table_name='object_permissions')
    op.drop_index(op.f('ix_object_permissions_resource'), table_name='object_permissions')
    op.drop_index(op.f('ix_object_permissions_object_id'), table_name='object_permissions')
    op.drop_table('object_permissions')
    # ### end Alembic commands ###
