"""add is_default to Role

Revision ID: 85a45012a7cf
Revises: 94e67626195e
Create Date: 2025-12-15 08:24:46.890231

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '85a45012a7cf'
down_revision = '94e67626195e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_roles_is_default'), 'roles', ['is_default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_is_default'), table_name='roles')
    op.drop_column('roles', 'is_default')
    # ### end Alembic commands ###
