"""Rename Fields, ...

Revision ID: 8bc82c37c679
Revises: 0d30f5919aaa
Create Date: 2025-12-09 07:34:33.494705

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bc82c37c679'
down_revision = '0d30f5919aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.drop_column('events', 'is_published')
    op.add_column('file', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False))
    op.add_column('file', sa.Column('relation_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True))
    op.add_column('file', sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.create_index(op.f('ix_file_relation_id'), 'file', ['relation_id'], unique=False)
    op.drop_constraint(op.f('file_ibfk_1'), 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'users', ['user_id'], ['id'])
    op.drop_column('file', 'uploaded_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('uploaded_by_id', mysql.VARCHAR(length=36), nullable=False))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(op.f('file_ibfk_1'), 'file', 'users', ['uploaded_by_id'], ['id'])
    op.drop_index(op.f('ix_file_relation_id'), table_name='file')
    op.drop_column('file', 'purpose')
    op.drop_column('file', 'relation_id')
    op.drop_column('file', 'user_id')
    op.add_column('events', sa.Column('is_published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('events', 'is_public')
    # ### end Alembic commands ###
