"""Add permissions relation to User

Revision ID: 8e418f39c2f9
Revises: 2a9f6b7fb8f9
Create Date: 2025-11-25 10:36:44.806939

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8e418f39c2f9'
down_revision = '2a9f6b7fb8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
