"""Add Companies and Company Employees, Also add oeak number to user

Revision ID: 94a0fc0c4946
Revises: af2709560c4e
Create Date: 2025-12-11 10:19:56.443123

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '94a0fc0c4946'
down_revision = 'af2709560c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oeak_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_oeak_id'), 'users', ['oeak_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_oeak_id'), table_name='users')
    op.drop_column('users', 'oeak_id')
    # ### end Alembic commands ###
