"""Remove migration congress data and add is_published

Revision ID: 99868941076a
Revises: 8e418f39c2f9
Create Date: 2025-11-25 14:15:08.657254

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99868941076a'
down_revision = '8e418f39c2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('congresses', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_congresses_migration_id'), table_name='congresses')
    op.drop_column('congresses', 'migration_id')
    op.drop_column('congresses', 'c_cat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('congresses', sa.Column('c_cat', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('congresses', sa.Column('migration_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_congresses_migration_id'), 'congresses', ['migration_id'], unique=False)
    op.drop_column('congresses', 'is_published')
    # ### end Alembic commands ###
