"""Remove the description from the Categories

Revision ID: aa74049fe81d
Revises: d88c7218c6e5
Create Date: 2025-12-01 14:03:02.615464

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa74049fe81d'
down_revision = 'd88c7218c6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
