"""the permission is now tagged to ask if an object bypass is allowed

Revision ID: ad5e83e05dea
Revises: 78eff1f641f2
Create Date: 2025-12-17 13:35:04.636279

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ad5e83e05dea'
down_revision = '78eff1f641f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('allow_object_bypass', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'allow_object_bypass')
    # ### end Alembic commands ###
