"""initial

Revision ID: af2709560c4e
Revises: 
Create Date: 2025-12-11 07:38:13.184466

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af2709560c4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_location_types_code'), 'location_types', ['code'], unique=True)
    op.drop_column('location_types', 'description')
    op.drop_column('locations', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('state', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('location_types', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_location_types_code'), table_name='location_types')
    # ### end Alembic commands ###
