"""Add max length of foreign ids

Revision ID: b067a2be3e75
Revises: 57faa1b4a894
Create Date: 2025-12-01 07:08:08.115477

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b067a2be3e75'
down_revision = '57faa1b4a894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
