"""add short name for Companies

Revision ID: b104f2f7f298
Revises: 12a17a8df844
Create Date: 2025-12-15 14:41:59.089814

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b104f2f7f298'
down_revision = '12a17a8df844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'short_name')
    # ### end Alembic commands ###
