"""Remove native name, names other than german names will be written in the translation files

Revision ID: b7df3f387d62
Revises: 1534389bac09
Create Date: 2025-11-25 07:19:32.087103

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7df3f387d62'
down_revision = '1534389bac09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'name_native')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('name_native', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
