"""Create Sponsoring table that stores all the sponsorings and is connected to a event

Revision ID: be4c7efef8e5
Revises: ea1ef44791fc
Create Date: 2025-12-15 12:28:23.895541

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'be4c7efef8e5'
down_revision = 'ea1ef44791fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsorings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['company_employees.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsorings')
    # ### end Alembic commands ###
