"""name of the sponsorings is not unique

Revision ID: c3d61ac02298
Revises: be4c7efef8e5
Create Date: 2025-12-15 12:35:22.427042

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c3d61ac02298'
down_revision = 'be4c7efef8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sponsorings_ibfk_2'), 'sponsorings', type_='foreignkey')
    op.create_foreign_key(None, 'sponsorings', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sponsorings', type_='foreignkey')
    op.create_foreign_key(op.f('sponsorings_ibfk_2'), 'sponsorings', 'companies', ['event_id'], ['id'])
    # ### end Alembic commands ###
