"""Add german and english translation for Event Category and Event Type

Revision ID: d88c7218c6e5
Revises: b77d4aa831cc
Create Date: 2025-12-01 13:59:31.453097

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd88c7218c6e5'
down_revision = 'b77d4aa831cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False))
    op.add_column('categories', sa.Column('name_de', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('categories', sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_code'), 'categories', ['code'], unique=True)
    op.create_index(op.f('ix_categories_name_de'), 'categories', ['name_de'], unique=True)
    op.create_index(op.f('ix_categories_name_en'), 'categories', ['name_en'], unique=True)
    op.drop_column('categories', 'name')
    op.add_column('event_types', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False))
    op.add_column('event_types', sa.Column('name_de', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('event_types', sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('event_types', sa.Column('description_de', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('event_types', sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_event_types_name'), table_name='event_types')
    op.create_index(op.f('ix_event_types_code'), 'event_types', ['code'], unique=True)
    op.create_index(op.f('ix_event_types_name_de'), 'event_types', ['name_de'], unique=True)
    op.create_index(op.f('ix_event_types_name_en'), 'event_types', ['name_en'], unique=True)
    op.drop_column('event_types', 'name')
    op.drop_column('event_types', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('event_types', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_event_types_name_en'), table_name='event_types')
    op.drop_index(op.f('ix_event_types_name_de'), table_name='event_types')
    op.drop_index(op.f('ix_event_types_code'), table_name='event_types')
    op.create_index(op.f('ix_event_types_name'), 'event_types', ['name'], unique=True)
    op.drop_column('event_types', 'description_en')
    op.drop_column('event_types', 'description_de')
    op.drop_column('event_types', 'name_en')
    op.drop_column('event_types', 'name_de')
    op.drop_column('event_types', 'code')
    op.add_column('categories', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_categories_name_en'), table_name='categories')
    op.drop_index(op.f('ix_categories_name_de'), table_name='categories')
    op.drop_index(op.f('ix_categories_code'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.drop_column('categories', 'name_en')
    op.drop_column('categories', 'name_de')
    op.drop_column('categories', 'code')
    # ### end Alembic commands ###
