"""Remove event type name and translation, this is unneccesary because it should be translated

Revision ID: dc10b683bfec
Revises: 20cda7a6f4a1
Create Date: 2025-12-11 10:35:05.015993

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc10b683bfec'
down_revision = '20cda7a6f4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_types_name_de'), table_name='event_types')
    op.drop_index(op.f('ix_event_types_name_en'), table_name='event_types')
    op.drop_column('event_types', 'description_de')
    op.drop_column('event_types', 'name_de')
    op.drop_column('event_types', 'description_en')
    op.drop_column('event_types', 'name_en')
    op.drop_index(op.f('ix_location_types_name'), table_name='location_types')
    op.drop_column('location_types', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_types', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.create_index(op.f('ix_location_types_name'), 'location_types', ['name'], unique=True)
    op.add_column('event_types', sa.Column('name_en', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('event_types', sa.Column('description_en', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('event_types', sa.Column('name_de', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('event_types', sa.Column('description_de', mysql.VARCHAR(length=255), nullable=True))
    op.create_index(op.f('ix_event_types_name_en'), 'event_types', ['name_en'], unique=True)
    op.create_index(op.f('ix_event_types_name_de'), 'event_types', ['name_de'], unique=True)
    # ### end Alembic commands ###
