"""Update information of user to use contact for contact detils and user for registered users

Revision ID: ea1ef44791fc
Revises: 85a45012a7cf
Create Date: 2025-12-15 12:11:30.906303

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql
import uuid
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'ea1ef44791fc'
down_revision = '85a45012a7cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    # Add new contact reference to company_employees first
    op.add_column('company_employees', sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'company_employees', 'contacts', ['contact_id'], ['id'])

    # --- Data migration: users -> contacts, and company_employees.user_id -> contact_id ---
    bind = op.get_bind()

    # Create one Contact per existing User, preserving names and email
    users = bind.execute(
        sa.text(
            """
            SELECT id, email, titles, first_name, last_name, created_at
            FROM users
            """
        )
    ).fetchall()

    if users:
        contact_rows = []
        for row in users:
            contact_rows.append(
                {
                    "id": str(uuid.uuid4()),
                    "email": row.email,
                    "titles": row.titles,
                    "first_name": row.first_name,
                    "last_name": row.last_name,
                    "phone_number": None,
                    "user_id": row.id,
                    "created_at": row.created_at or datetime.utcnow(),
                }
            )

        bind.execute(
            sa.text(
                """
                INSERT INTO contacts
                    (id, email, titles, first_name, last_name, phone_number, user_id, created_at)
                VALUES
                    (:id, :email, :titles, :first_name, :last_name, :phone_number, :user_id, :created_at)
                """
            ),
            contact_rows,
        )

        # Backfill company_employees.contact_id using the newly created contacts
        bind.execute(
            sa.text(
                """
                UPDATE company_employees ce
                JOIN contacts c ON c.user_id = ce.user_id
                SET ce.contact_id = c.id
                WHERE ce.user_id IS NOT NULL AND ce.contact_id IS NULL
                """
            )
        )

    # Now safely drop old FK and column to users, and remove name fields from users
    op.drop_constraint(op.f('company_employees_ibfk_2'), 'company_employees', type_='foreignkey')
    op.drop_column('company_employees', 'user_id')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'titles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('titles', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('company_employees', sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True))
    # Restore data from contacts before dropping columns/tables
    bind = op.get_bind()
    # Move names back to users from contacts
    bind.execute(
        sa.text(
            """
            UPDATE users u
            JOIN contacts c ON c.user_id = u.id
            SET u.first_name = c.first_name,
                u.last_name = c.last_name,
                u.titles = c.titles
            """
        )
    )
    # Restore company_employees.user_id from contact linkage
    bind.execute(
        sa.text(
            """
            UPDATE company_employees ce
            JOIN contacts c ON c.id = ce.contact_id
            SET ce.user_id = c.user_id
            WHERE ce.contact_id IS NOT NULL
            """
        )
    )
    op.drop_constraint(None, 'company_employees', type_='foreignkey')
    op.create_foreign_key(op.f('company_employees_ibfk_2'), 'company_employees', 'users', ['user_id'], ['id'])
    op.drop_column('company_employees', 'contact_id')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
