"""Add Preferred tag to countries for selection of event

Revision ID: f7118926de35
Revises: 322851ef48bf
Create Date: 2025-12-02 09:38:47.607864

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f7118926de35'
down_revision = '322851ef48bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('preferred', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'preferred')
    # ### end Alembic commands ###
